package com.identity.platform.persistence.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "orgsec_db", uniqueConstraints = @UniqueConstraint(columnNames = { "NAME", "CODE" }))
public class Status extends AbstractJpaAuditLog<BasicJpaUser, Long> {

	private static final long serialVersionUID = 1L;

	@Column(name = "NAME", nullable = false, length = 50, unique = true)
	private String name;

	@Column(name = "CODE", nullable = false)
	private long code;

	@Column(name = "DESCRIPTION", length = 250)
	private String description;

	public Status() {

	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getCode() {
		return code;
	}

	public void setCode(long code) {
		this.code = code;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
